config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      resources :tours, only: %i[index show create update destroy] do
        resources :photos, only: %i[index show create update destroy]
      end

      resources :tourbooks
      resources :guidebooks

      resources :users, only: %i[show] do
        collection do
          get 'current_account'
        end

        resources :tourbooks, only: %i[index]
      end

      post '/viewpoints', to: 'photos#set_viewpoints'
      get '/viewpoints', to: 'photos#get_viewpoints'
      get '/users', to: 'users#get_info'

      get '*unmatched_route', to: 'base#user_not_authorized', code: 401
    end
  end

  resources :users, only: %i[show] do
    post 'generate_new_token', to: 'users#generate_new_token'
    post 'submit_request_apikey', to: 'users#submit_request_apikey'

    resources :tours

    resources :tourbooks do
      member do
        post 'add_item', to: 'tourbooks#add_item'
        delete 'remove_item', to: 'tourbooks#remove_item'
      end
    end

    get 'viewpoints', to: 'photos#viewpoints'

    resources :guidebooks do
      resources :scenes do
        resources :photo, only: %i[show], to: 'photos#guidebook_scene_photo'
        get 'guidebook_scenes', to: 'scenes#guidebook_scenes'
        delete 'remove_photo', to: 'guidebooks#remove_photo'
      end
      member do
        post 'add_photo', to: 'guidebooks#add_photo'
      end
    end
  end

  resources :photos, only: %i[show]

  resources :tours, only: %i[index show]
  resources :tourbooks, only: %i[index show]
  get '/viewpoints', to: 'photos#viewpoints'
  resources :guidebooks, only: %i[index show]
  resources :scenes, only: %i[index show]

  get '/search_tours', to: 'tours#search_tours'
  get '/sitemap.xml', to: 'application#sitemap'
  get '/robots.txt' => 'robots_txts#show'
  get '/about', to: 'home#about'
  get '/upload', to: 'home#upload'
  get '/select_scene_photo', to: 'scenes#select_scene_photo', as: 'select_scene_photo'
  post '/select_scene', to: 'guidebooks#select_scene', as: 'select_scene'

  root to: 'home#index'
end

app/controllers/api/v1/guidebooks_controller.rb
# frozen_string_literal: true
module Api::V1
  class GuidebooksController < Api::V1::BaseController
    before_action :set_guidebook, only: %i[show update destroy]
    before_action :set_user
    before_action :seperate_guidebook_and_scenes_params, only: %i[create update]
    before_action :set_guidebooks_search_params, only: %i[find_guidebooks]
    before_action :validate_name, only: %i[update]
    before_action :validate_guidebooks, only: %i[create update]

    # GET /api/v1/guidebooks
    def index
      find_guidebooks
      @guidebooks = @guidebooks.page(params[:page] ? params[:page].to_i : 1)
      guidebooks_json = ActiveModelSerializers::SerializableResource.new(
        @guidebooks
      ).as_json
      guidebooks_json['_metadata'] = pagination_meta(@guidebooks)
      render json: guidebooks_json, status: :ok
    end

    # GET /api/v1/guidebooks/:id
    def show
      render json: @guidebook, status: :ok
    end

    # POST /api/v1/guidebooks
    def create
      # Create guidebook
      @guidebook = api_user.guidebooks.build(@guidebook_params)
      return response_unprocessable(@guidebook.errors) unless @guidebook.save

      # Create scenes
      @scenes_params.each do |scene_param|
        scene_param_only = scene_param.except(:tags)
        scene = @guidebook.scenes.build(scene_param_only)
        tag_param = scene_param.delete(:tags)
        return response_unprocessable(scene.errors) unless scene.save

        # if scene_param[:tags] && scene_param.tags.size.positive?
        if tag_param && tag_param.size.positive?
          # scene.tag_list = tag_param
          scene.tags = tag_param.map do |n|
            Tag.where(name: n.strip).first_or_create!
          end
        end
      end
      guidebook_json = ActiveModelSerializers::SerializableResource.new(
        @guidebook
      ).as_json
      render json: guidebook_json, status: :created
    end

    # PATCH/PUT /api/v1/guidebooks/:id
    def update
      return response_unauthorized('You cannot update this guidebook') unless
        api_user.guidebooks.include?(@guidebook)
      return response_unprocessable(@guidebook.errors) unless
        @guidebook.update(@guidebook_params)

      if @scenes_params.size.positive?
        # Delete previous scenes
        @guidebook.scenes.map { |s| s.scenes_tags.delete_all }
        @guidebook.scenes.delete_all

        # Create new scenes with scene params
        @scenes_params.each do |scene_param|
          scene_param_only = scene_param.except(:tags)
          scene = @guidebook.scenes.build(scene_param_only)
          tag_param = scene_param.delete(:tags)
          return response_unprocessable(scene.errors) unless scene.save

          # if scene_param[:tags] && scene_param.tags.size.positive?
          if tag_param && tag_param.size.positive?
            # scene.tag_list = tag_param
            scene.tags = tag_param.map do |n|
              Tag.where(name: n.strip).first_or_create!
            end
          end
        end
        # @scenes_params.each do |scene_params|
        #   scene = @guidebook.scenes.find(scene_params[:id])
        #   return response_unprocessable(scene.errors) unless
        #     scene.update(scene_params)
        # end
      end
      render json: @guidebook, status: :created
    end

    # DELETE /api/v1/guidebooks/:id
    def destroy
      return response_unauthorized('You cannot delete this Guidebook.') unless
        user_guidebook?

      @guidebook.scenes.map { |s| s.scenes_tags.delete_all }
      @guidebook.scenes.delete_all
      @guidebook.destroy
      return response_unprocessable(@guidebook.errors) if @guidebook.errors.any?

      render json: {
        guidebook: { id: @guidebook.id, deleted_at: DateTime.now.rfc3339 }
      }, status: :ok
    end

    # GET /api/v1/users/:user_id/guidebooks
    def user_guidebooks
      return response_forbidden('You can get only your own guidebooks.') if
        api_user == @user

      find_guidebooks
      @guidebooks = @guidebooks.page(params[:page] ? params[:page].to_i : 1)
      guidebooks_json = ActiveModelSerializers::SerializableResource.new(
        @guidebooks
      ).as_json
      guidebooks_json['_metadata'] = pagination_meta(@guidebooks)
      render json: guidebooks_json, status: :ok
    end

    def response_unauthorized(message)
      render json: {
        status: :unauthorized,
        message: message
      }, status: :unauthorized
    end

    def response_forbidden(message)
      render json: {
        status: :forbidden,
        message: message
      }, status: :forbidden
    end

    def response_unprocessable(message)
      render json: {
        status: :unprocessable_entity,
        message: message
      }, status: :unprocessable_entity
    end

    private

    def set_guidebook
      @guidebook = Guidebook.find_by(id: params[:id])
    end

    def guidebook_params
      params.permit(
        :id, :name, :description, :category_id, :user_id,
        scenes: [
          :id, :photo_id, :description, :position,
          :title, :tags, { tags: [] }
        ]
      )
    end

    def seperate_guidebook_and_scenes_params
      @guidebook_params = guidebook_params.except(:scenes)
      @scenes_params = guidebook_params.delete(:scenes)
    end

    def set_user
      @user = @api_user
    end

    def permitted_params
      %i[name description category_id user_id scenes]
    end

    def find_guidebooks
      @guidebooks = @user ? @user.guidebooks : Guidebook.all
      set_guidebooks_search_params
      if @query.present?
        if @query[:sort_by].present?
          order_direction = @query[:sort_by] == 'name' ? 'ASC' : 'DESC'
          @guidebooks = @guidebooks.order(
            "#{@query[:sort_by]} #{order_direction}"
          )
        end
        @guidebooks = @guidebooks.where(id: @query[:ids]) if @query[:ids].present?
        @guidebooks = @guidebooks.includes(:scenes).where('scenes.photo_id IN (?)', @query[:photo_ids]).references(:scenes) if @query[:photo_ids].present?
        @guidebooks = @guidebooks.where(user_id: @query[:user_ids]) if @query[:user_ids].present?
        @guidebooks = @guidebooks.page(@query[:page].to_i) if @query[:page]
      end
      @guidebooks = @guidebooks.order(updated_at: :desc)
    end

    def set_guidebooks_search_params
      @query = guidebook_search_params
    end

    def guidebook_search_params
      params.permit(
        :sort_by, :page,
        ids: [], photo_ids: [], user_ids: []
      )
    end

    def pagination_meta(object)
      {
        current_page: object.current_page,
        per_page: Constants::ITEMS_PER_PAGE[:guidebooks],
        next_page: object.next_page,
        prev_page: object.prev_page,
        total_pages: object.total_pages,
        total_count: object.total_count
      }
    end

    def validate_guidebooks
      return unless
        params[:guidebook].present? && guidebook_params[:scenes].empty?

      response_unprocessable('Guidbook IDs are all invalid.')
    end

    def validate_name
      return unless guidebook_params[:name].present?

      response_unprocessable('you cannot change the name of a guidebook.')
    end

    def user_guidebook?
      api_user.guidebooks.include?(@guidebook)
    end
  end
end

app/controllers/guidebooks_controller.rb
class GuidebooksController < ApplicationController
  include MetaTagsHelper

  before_action :authenticate_user!, except: %i[index show select_scene]
  before_action :set_user
  before_action :set_guidebook, except: %i[index new create remove_photo select_scene]
  before_action :set_guidebook_for_remove_photo, only: %i[remove_photo]
  before_action :authorize_guidebook, only: %i[
    edit update destroy add_photo remove_photo
  ]
  before_action :set_scenes, only: %i[show edit update destroy]
  before_action :sort_scenes, only: %i[show edit]
  before_action :set_tab, only: %i[new create index show]
  before_action :set_guidebooks_search_params, only: [:index]

  def index
    @guidebooks = @user ? @user.guidebooks : Guidebook.all
    search_guidebooks
    @guidebooks.order(created_at: :desc)
    @guidebooks = @guidebooks.page(params[:page]).per(
      Constants::WEB_ITEMS_PER_PAGE[:guidebooks]
    )
  end

  def show
    @current_scene = @guidebook.scenes[0]
    return unless @current_scene

    @photo = @current_scene ? @current_scene.photo : nil
    @tour = @photo.tour
    photo_og_meta_tag(@photo)
    gon.pannellum_config = guidebook_pannellum_config
    gon.scenes = @guidebook.scenes
    gon.photos = @guidebook.photos
    gon.tour_name = @tour.name
    gon.scene_title = @current_scene.title
    gon.scene_id = @current_scene.id
    gon.scene_description = @current_scene.description
    gon.guidebook_name = @guidebook.name
    gon.guidebook_description = @guidebook.description
    gon.author_name = @guidebook.user.name
    gon.root_url = root_url
  end

  def new
    @guidebook = Guidebook.new
  end

  def create
    @guidebook = current_user.guidebooks.build(guidebook_params)
    authorize @guidebook

    respond_to do |format|
      if @guidebook.save
        add_photo
        flash[:success] = 'You Guidebook was created!'
        format.html { redirect_to user_guidebooks_path(@user) }
      else
        format.html { render :new }
      end
      format.js
    end
  end

  def edit; end

  def update
    if @guidebook.update(guidebook_params)
      flash[:success] = 'Your guidebook was updated!'
      redirect_to user_guidebook_path(@user, @guidebook)
    else
      flash[:error] = @guidebook.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @guidebook.scenes.map { |s| s.scenes_tags.delete_all }
    @guidebook.scenes.delete_all
    @guidebook.delete
    flash[:success] = "Guidebook #{@guidebook.name} was destroyed"
    redirect_to user_guidebooks_path(@user)
  end

  def add_photo
    return unless params[:photo_id].present?

    if @guidebook.have_photo(params[:photo_id])
      flash.now[:error] = "The photo already was added in the guidebook."
      return
    end

    begin
      @scene = Scene.create(
        guidebook_id: @guidebook.id,
        description: '',
        position: @guidebook.last_position + 1,
        photo_id: params[:photo_id]
      )
      @photo = Photo.find(params[:photo_id])
      flash.now[:notice] = "
        The photo was added to your Guidebook #{@guidebook.name}
      "
    rescue ActiveRecord::RecordInvalid => e
      flash.now[:error] = e.message
    end
  end

  def remove_photo
    return unless params[:photo_id].present?

    @scene = Scene.find(params[:scene_id])
    begin
      @scene.delete
      flash[:success] = "
        Scene \"#{@scene.description}\" was removed from this Guidebook
      "
    rescue ActiveRecord::RecordNotDestroyed => e
      flash[:error] = e.message
    end
  end

  def select_scene
    @current_scene = Scene.find(params[:scene_id])
    @guidebook = @current_scene.guidebook
    @photo = @current_scene.photo
    @tour = @photo.tour

    photo_og_meta_tag(@photo)
    gon.pannellum_config = guidebook_pannellum_config
    gon.photos = @guidebook.photos
    gon.scenes = @guidebook.scenes
    gon.tour_name = @tour.name
    gon.scene_title = @current_scene.title
    gon.scene_id = @current_scene.id
    gon.scene_description = @current_scene.description
    gon.guidebook_name = @guidebook.name
    gon.guidebook_description = @guidebook.description
    gon.author_name = @guidebook.user.name
    gon.root_url = root_url

    respond_to do |format|
      format.js
    end
  end

  private

  def set_guidebook
    @guidebook = Guidebook.find(params[:id])
  end

  def set_scenes
    @scenes = @guidebook.scenes.order(:position)
  end

  def set_tab
    @tab = 'guidebooks'
  end

  def authorize_guidebook
    authorize @guidebook
  end

  def guidebook_params
    params.require(:guidebook).permit(*permitted_params)
  end

  def permitted_params
    %i[name description category_id user_id scenes]
  end

  def set_user
    @user = if params[:user_id]
              User.friendly.find(params[:user_id])
            elsif params[:user]
              User.friendly.find(params[:id])
            end
  end

  def set_sort_params
    @sort = sort_params[:sort]
  end

  def sort_params
    params.permit(sort: [:scenes])
  end

  def sort_scenes
    set_sort_params

    if @sort.present?
      @scenes = @scenes.order(:name) if @sort[:name] == 'name'
      @scenes = @scenes.order(:position) if @sort[:scenes] == 'position'
      @scenes = @scenes.order(positions_count: :desc) if
        @sort[:scenes] == 'scenes_count'
    end
    @scenes = @scenes.order(:position)
  end

  def set_guidebooks_search_params
    @search_text = guidebooks_search_params[:search_text]
  end

  def guidebooks_search_params
    params.permit(:search_text)
  end

  def search_guidebooks
    # @guidebooks = @guidebooks.search(@search_text) if @search_text.present?
    if @search_text.present?
      @guidebooks = @guidebooks.where(
        'lower(name) LIKE ?', '%' + @search_text.downcase + '%'
      ).or(
        @guidebooks.where(
          'lower(description) LIKE ?', '%' + @search_text.downcase + '%'
        )
      )
    end
  end

  def set_guidebook_for_remove_photo
    @guidebook = Guidebook.find(params[:guidebook_id])
  end

  def guidebook_pannellum_config
    options = {
      "autoLoad": true,
        "default": {
            "firstScene": @guidebook.scenes[0].id,
            "title": @current_scene.description,
            "author": @guidebook.user.name,
            "authorURL": photo_path(@photo),
            "sceneFadeDuration": 0
        },
        "scenes": {}
    }

    @guidebook.scenes.each do |scene|
      photo = scene.photo
      next unless photo.tourer["connections"]
      begin
        connections = JSON.parse(photo.tourer["connections"])
        hot_spots = []
        connections&.keys&.each do |key|
          hot_photo = photo.tour.photos.select{ |connected_photo| connected_photo.tourer_photo_id == connections[key]["photo_id"] }.first
          if hot_photo
            hot_spots << {
                "type": "scene",
                "pitch": connections[key]["pitch_degrees"].to_f,
                "yaw": connections[key]["adjusted_heading_degrees"].to_f,
                "text": hot_photo.tourer_photo_id,
                "sceneId": scene.id #hot_photo.tourer_photo_id
            }
          end
        end
      rescue => exception
        puts "=== exception: #{exception.inspect}"
      end

      options[:scenes][scene.id] = {
        "title": scene.description,
        "author": @guidebook.user.name,
        "authorURL": photo_path(photo),
        "type": "equirectangular",
        "panorama": photo.image_path,
        "hotSpots": hot_spots
      }
    end

    options
  end
end

app/helpers/guidebooks_helper.rb
module GuidebooksHelper
end

app/views/guidebooks/_form.html.erb
<% form_url = @guidebook.new_record? ? user_guidebooks_path : user_guidebook_path %>

<%= form_with(model: @guidebook, url: form_url, local: true) do |f| %>

  <%= form_errors_for @guidebook %>
  <div class="h-divider-empty"></div>
  <div class="form-group float-right">
    <%= link_to(
          'Back',
          @guidebook.new_record? ? 
            user_path(current_user) : 
            user_guidebook_path(id: @guidebook.id),
          class: 'btn btn-success'
        )
    %>
    <% button_text = @guidebook.new_record? ? 'Create' : 'Update' %>
    <%= f.submit button_text , class: 'btn btn-primary' %>
  </div>

  <h4><p>Guidebook Info</p></h4>
  <div class="h-divider"></div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select(
          :category_id, Category.order(:name), :id, :name,
          { prompt: "Select a category" },
          { class: "form-control", include_blank: true }
        )
    %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field(
          :name, autofocus: true, autocomplete: 'name',
          maxlength: 70, class: 'form-control'
        )
    %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, autocomplete: 'description', class: 'form-control', size: '60x3', maxlength: 250 %>
  </div>

<% end %>

app/views/guidebooks/_guidebook.html.erb
<div class="card photo-card h-100">
  <span class="badge badge-pill badge-success badge-count" title="Added to Guidebook">
    <%= guidebook.scenes_count %>
  </span>
  <% thumb_url = guidebook_thumb_url(guidebook) %>
  <% if thumb_url.present? %>
    <img class="card-img-top" src="<%= thumb_url %>" alt="">
  <% end %>
  <div class="card-body">
    <h4 class="card-title">
      <%= link_to guidebook.name, @user.present? ? user_guidebook_path(@user, guidebook) : guidebook_path(guidebook)%>
    </h4>

    <p class="card-text">
      <%= truncate(guidebook.description, length: 120, separator: ' ') %>
    </p>
  </div>

  <div class="card-footer">
    <small class="text-muted">
      created by: 
      <% if owner?( guidebook.user.id) %>
        <%= link_to guidebook.user.try(:name), edit_user_registration_path(@user) %>
      <% else %>
        <%= guidebook.user.try(:name) %>
      <% end %>
    </small>
  </div>
</div>

app/views/guidebooks/_guidebook_filter.html.erb
<h5>Filters</h5>
<%= form_tag(@user.present? ? user_guidebooks_path : guidebooks_path, method: :get, class: 'index-search-form page-item-search clearfix') do %>
  <div class="search-text clearfix">
    <div class="search-input mt-3">
      <%= text_field_tag 'search_text',
            @search_text, 
            class: 'search-text-input with-img form-control',
            placeholder: 'Search for guidebook'
      %>
    </div>

    <button class="btn btn-primary mt-3">Filter</button>

  </div>
<% end %>

app/views/guidebooks/_guidebooks_display.html.erb
<div class="row">
  <% guidebooks.each do |guidebook| %>
    <div class="col-xl-4 col-lg-4 col-md-6 mb-4">
      <%= render partial: 'guidebooks/guidebook', locals: { guidebook: guidebook } %>
    </div>
  <% end %>
</div>

app/views/guidebooks/_user_guidebook_scenes.html.erb
<div class="float-right">
  <%= link_to 'Add scene', new_user_guidebook_scene_path(user_id: @user.id, guidebook_id: @guidebook.id), class: 'btn btn-primary' %>
</div>

<h4>Added Scenes</h4>
<div class="h-divider"></div>

<% if @scenes.any? %>
  <div class="sort-wrapper">
    <%= render(
          SortComponent, collection_name: :scenes,
          value: @sort.try(:[], :scenes)
        )
    %>
  </div>
  <div class="row">
    <%= render partial: 'scenes/scene', collection: @scenes %>
  </div>
<% else %>
  <p class="card-text">Nothing</p>
<% end %> 

app/views/guidebooks/add_photo.js.erb
var messages = $('.flash-messages');
messages.html('');
messages.html('<%= j render partial: "shared/flash_messages" %>');

app/views/guidebooks/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="my-4">
      <%= title "Edit Guidebook #{@guidebook.name}" %>
    </h1>
    <% description app_description %>
  </div>

  <div class="col-lg-12">
    <%= render 'form' %>

    <div class="h-divider-empty"></div>
    <div class="h-divider-empty"></div>
    <div class="h-divider-empty"></div>

    <%= render 'guidebooks/scenes/scenes'%>
  </div>
</div>

app/views/guidebooks/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-9 col-sm-12">
        <h1 class="my-4">
          <%= @user.present? ? 'My guidebooks' : 'Guidebooks' %>
        </h1>
        <% description app_description %>
      </div>
      <% if @user.present? %>
        <div class="col-lg-3 col-sm-12 mt-4">
          <%= link_to(
                "New Guidebook",
                new_user_guidebook_path(@user),
                class: 'btn btn-primary float-right'
              )
          %>
        </div>
      <% end %>
    </div>

    <div class="row mt-4">
      <div class="col-lg-3">
        <%= render partial: 'guidebook_filter' %>
      </div>

      <div class="col-lg-9">
        <div class="guidebooks-container">
          <% if @guidebooks.size.positive? %>
            <%= render partial: 'guidebooks_display', locals: {guidebooks: @guidebooks} %>
            <%= paginate @guidebooks %>
          <% else %>
            <p class="nothing-text">
              No results matched your search criteria, try a different search instead.
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/guidebooks/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="my-4"><%= title 'New Guidebook' %></h1>
    <% description app_description %>
  </div>

  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/guidebooks/remove_item.js.erb
var messages = $('.flash-messages');
messages.html('<%= j render partial: "shared/flash_messages" %>');
$("#tour-<%= @tour.id %>").remove();

app/views/guidebooks/remove_photo.js.erb
var messages = $('.flash-messages');
messages.html('<%= j render partial: "shared/flash_messages" %>');
$("#scene-<%= @scene.id %>").remove();

app/views/guidebooks/select_scene.js.erb
$("#guidebook-scene-description").html("<%= escape_javascript(render partial: 'guidebooks/scene_description', locals: {scene: @current_scene, photo: @photo}) %>");
$("#scene-nav-index").html("<%= (@current_scene.index + 1) %>");

app/views/guidebooks/show.html.erb
<% content_for :meta_title do %>
  <% @guidebook.name %>
<% end %>

<% content_for :meta_description do %>
  <% @guidebook.description %>
<% end %>

<div class="row">
  <div class="py-5 col-lg-12">
    <div class="card">

      <div class="card-header">
        <div class="row">

          <h1 class="col-lg-10 col-sm-12">
            <%= title "#{@guidebook.name} guidebook" %>
          </h1>
          <% description @guidebook.description %>

          <% if @user.present? %>
            <% if policy(@guidebook).update? %>
              <div class="col-lg-1 col-sm-6">
                <div class="float-right">
                  <%= link_to 'Edit',
                    edit_user_guidebook_path(@guidebook.user, @guidebook),
                    class: 'btn btn-warning mt-2'
                  %>
                </div>
              </div>
            <% end %>

            <% if policy(@guidebook).destroy? %>
              <div class="col-lg-1 col-sm-6">
                <div class="float-right">
                  <%= link_to 'Delete',
                              url_for(action: :destroy, id: @guidebook.id),
                              method: :delete,
                              data: {confirm: 'Are you sure?'},
                              class: 'btn btn-danger mt-2'%>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="card-body">

        <h3 class="card-title"><%= @guidebook.name %></h3>

        <div class="row">
          <label class="col-sm-2"><strong>Description</strong></label>
          <div class="col-sm-10 mt-1">
            <p><%= @guidebook.description %></p>
          </div>
        </div>
        <div class="row">
          <label class="col-sm-2"><strong>Category</strong></label>
          <div class="col-sm-10 mt-1">
            <p><%= @guidebook.category.name %></p>
          </div>
        </div>
        
        <h3 class="card-title">Scenes</h3>
         <%= render partial: 'guidebooks/scenes_navigation/view', locals: { guidebook: @guidebook, current_scene: @current_scene } %>

        <h3 class="card-title">Guidebook sponsors</h3>

        <% if @guidebook.sponsors.size.positive? %>
          <%= render partial: 'sponsors/sponsors_display', locals: { sponsors: @guidebook.sponsors } %>
        <% else %>
          <%= render 'sponsors/default_sponsors' %>
        <% end %>

    </div>
  </div>
</div>
</div>


<div class="form-group">
  <%= link_to 'Back', @user.present? ? user_guidebooks_path(@user) : guidebooks_path(), class: 'btn btn-success' %>
</div>

<script>
  $(function() {
    console.log('==== gon: ', gon);
    if (gon.pannellum_config === undefined) {
      return false;
    }
    markers = [];
    viewer = pannellum.viewer('panorama', gon.pannellum_config);
    console.log('==== viewer: ', viewer);
    initGuidebookMapBox(gon.scenes, gon.photos);

    currentScene = viewer.getScene();
    if (currentScene) {
      currentMarker = markers.find(obj => obj.tourer_photo_id == currentScene);
      if (currentMarker) {
        // currentMarker.setAnimation(google.maps.Animation.BOUNCE);
        currentMarker.bounce({duration: 5000, height: 100});
      }
    }

    viewer.on('scenechange', function () {
      hotSpot = gon.pannellum_config.scenes[currentScene].hotSpots.find(obj => obj.sceneId == viewer.getScene());
      photo = gon.photos.find(obj => obj.tourer_photo_id == viewer.getScene());
      if (photo) {
        const s3dom = document.getElementById('aws-s3-bucket-name').childNodes;
        const s3name = s3dom[0].data;
        iframe_url = '<iframe width="600" height="400" allowfullscreen style="border-style:none;" src="' + 
        'https://' + s3name + '/static/pannellum/pannellum.htm' + 
        '#panorama=' + 
          photo.image_path + 
          '&amp;title=' + encodeURIComponent(gon.scene_title) + 
          '&amp;author=' + encodeURIComponent(gon.author_name) + 
          '&amp;autoLoad=true"></iframe><p><a href="' + 
          gon.root_url + 'photos/' + photo.id + 
          '" target="_blank">View on Trek View Explorer</a></p>';

        $('.custom-tooltip').text(iframe_url);
      }

      if (hotSpot) {
        viewer.setYaw(hotSpot.yaw);
      }

      prevMarker = markers.find(obj => obj.tourer_photo_id == currentScene);

      currentScene = viewer.getScene();

      currentMarker = markers.find(obj => obj.tourer_photo_id == currentScene);

      if (prevMarker) prevMarker.drop();
      if (currentMarker) {
        console.log('==== currentMarker: ', currentMarker);
        // currentMarker.bounce({duration: 5000, height: 100});
      }

      // prevMarker.setAnimation(google.maps.Animation.DROP);
      // currentMarker.setAnimation(google.maps.Animation.BOUNCE);
    });
  });
</script>

app/views/guidebooks/user_guidebooks.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-9 col-sm-12">
        <h1 class="my-4"><%= title 'Your Guidebooks' %></h1>
        <% description app_description %>
      </div>

      <div class="col-lg-3 col-sm-12 mt-4">
        <%= link_to(
              "New Guidebook",
              new_user_guidebook_path(current_user),
              class: 'btn btn-primary float-right'
            )
        %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="row guidebooks-container">
          <%= render 'user_guidebooks' %>
        </div>
      </div>
    </div>
    <%= paginate @guidebooks %>
  </div>
</div>