config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      resources :tours, only: %i[index show create update destroy] do
        resources :photos, only: %i[index show create update destroy]
      end

      resources :tourbooks
      resources :guidebooks

      resources :users, only: %i[show] do
        collection do
          get 'current_account'
        end

        resources :tourbooks, only: %i[index]
      end

      post '/viewpoints', to: 'photos#set_viewpoints'
      get '/viewpoints', to: 'photos#get_viewpoints'
      get '/users', to: 'users#get_info'

      get '*unmatched_route', to: 'base#user_not_authorized', code: 401
    end
  end

  resources :users, only: %i[show] do
    post 'generate_new_token', to: 'users#generate_new_token'
    post 'submit_request_apikey', to: 'users#submit_request_apikey'

    resources :tours

    resources :tourbooks do
      member do
        post 'add_item', to: 'tourbooks#add_item'
        delete 'remove_item', to: 'tourbooks#remove_item'
      end
    end

    get 'viewpoints', to: 'photos#viewpoints'

    resources :guidebooks do
      resources :scenes do
        resources :photo, only: %i[show], to: 'photos#guidebook_scene_photo'
        get 'guidebook_scenes', to: 'scenes#guidebook_scenes'
        delete 'remove_photo', to: 'guidebooks#remove_photo'
      end
      member do
        post 'add_photo', to: 'guidebooks#add_photo'
      end
    end
  end

  resources :photos, only: %i[show]

  resources :tours, only: %i[index show]
  resources :tourbooks, only: %i[index show]
  get '/viewpoints', to: 'photos#viewpoints'
  resources :guidebooks, only: %i[index show]
  resources :scenes, only: %i[index show]

  get '/search_tours', to: 'tours#search_tours'
  get '/sitemap.xml', to: 'application#sitemap'
  get '/robots.txt' => 'robots_txts#show'
  get '/about', to: 'home#about'
  get '/upload', to: 'home#upload'
  get '/select_scene_photo', to: 'scenes#select_scene_photo', as: 'select_scene_photo'
  post '/select_scene', to: 'guidebooks#select_scene', as: 'select_scene'

  root to: 'home#index'
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :photo
  belongs_to :guidebook
  has_many :scenes_tags, dependent: :delete_all
  has_and_belongs_to_many :tags

  def guidebook_scenes_ids
    guidebook.scenes.ids
  end

  def index
    guidebook_scenes_ids.index(id)
  end

  def prev_scene_id
    current_index = index
    return guidebook_scenes_ids[current_index - 1] if current_index >= 1

    guidebook_scenes_ids.first
  end

  def prev_scene
    guidebook.scenes.find(prev_scene_id)
  end

  def next_scene_id
    current_index = index
    return guidebook_scenes_ids[current_index + 1] if current_index < (guidebook_scenes_ids.size - 1)

    guidebook_scenes_ids.last
  end

  def next_scene
    guidebook.scenes.find(next_scene_id)
  end

  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name)
  end

  def tag_list_string
    tag_list.join(',')
  end

  def tag_list=(names)
    console.log('====== names: ', names)
    self.tags = names.map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_user_and_guidebook, except: [:select_scene_photo]
  before_action :set_scene, only: %i[show edit update destroy]

  def index
    @scenes = @guidebook.scenes
  end

  def show; end

  def new
    @scene = Scene.new(guidebook_id: @guidebook.id)
  end

  def create
    # @scene = Scene.create(scene_params)
    @scene = @guidebook.scenes.build(scene_params)
    render :new unless @guidebook.save

    flash[:success] = 'Your scence was created!'
    redirect_to edit_user_guidebook_path(id: @guidebook.id)
  end

  def edit; end

  def update
    puts("===== scene_params: #{params}")
    puts("===== scene_params: #{scene_params}")
    if @scene.update(scene_params)
      flash[:success] = 'Your scene was updated!'
      redirect_to user_guidebook_path(@user, @guidebook)
    else
      flash[:error] = @scene.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @scene.destroy
    redirect_to user_guidebook_path(@user, @guidebook)
  end

  def guidebook_scenes
    @scenes = @guidebook.scenes
  end

  def select_scene_photo
    @photo = Photo.find_by(id: params[:photo_id])
    respond_to do |format|
      format.js
    end
  end

  private

  def set_user_and_guidebook
    @user = User.friendly.find(params[:user_id])
    @guidebook = Guidebook.find_by_id(params[:guidebook_id])
  end

  def set_scene
    @scene = Scene.find_by_id(params[:id])
  end

  def scene_params
    params.require(:scene).permit(*permitted_params)
  end

  def permitted_params
    [
      :guidebook_id, :photo_id, :title, :position, :description,
      :tag_list, :tag, :tag_ids, { tag_ids: [] }
    ]
  end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_form.html.erb
<div class="row">
  <div class="col-6">
    <% form_url = @scene.new_record? ?
        user_guidebook_scenes_path :
        user_guidebook_scene_path
    %>

    <%= simple_form_for @scene, url: form_url do |f| %>

      <%= form_errors_for @scene %>
      <div class="h-divider-empty"></div>
      <div class="form-group float-right">
        <%= link_to 'Back', :back, class: 'btn btn-success' %>
        <% button_text = @scene.new_record? ? 'Create' : 'Update' %>
        <%= f.submit button_text , class: 'btn btn-primary' %>
      </div>

      <h4><p><%= @scene.new_record? ? "New Scene" : "Scene" %></p></h4>
      <div class="h-divider"></div>
     
      <div class="form-group">
        <%= f.label :guidebook_id %>
        <%= f.collection_select(
              :guidebook_id, Guidebook.order(:name), :id, :name, {},
              { class: "form-control", disabled: "disabled" }
            )
        %>
      </div>
      
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field(
              :title, value: @scene.title, class: 'form-control'
            )
        %>
      </div>

      <div class="form-group">
        <%= f.label :position %>
        <%= f.number_field(
              :position, value: @scene.position, min: 0, class: 'form-control'
            )
        %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area(
              :description, autocomplete: 'description',
              class: 'form-control', size: '60x3', maxlength: 250
            )
        %>
      </div>

      <div class="form-group">
        <%= f.input :tag_ids, label: 'Tags', as: :select, collection: Tag.order(:name), label_method: :name, input_html: {multiple: true} %>
      </div>
    <% end %>
  </div>

  <div class="col-6">
    <div id="guidebook-scene-photo">
      <% if @scene.photo.present? %>
        <%= render partial: 'photos/photo',
            locals: { photo: @scene.photo,
              photo_link: @user.present? ? 
                user_guidebook_scene_photo_path(@user,  @guidebook, @scene, id: @scene.photo.id) :
                photo_path(@scene.photo)
            }
        %>
      <% end %>
    </div>
  </div>
  <div class="col-12">
    <% unless @scene.new_record? %>
      <% if policy(@scene).destroy? %>
        <%= link_to 'Delete',
            user_guidebook_scene_path(
              user_id: @user.id,
              guidebook_id: @guidebook.id,
              id: @scene.id
            ),
            method: :delete,
            data: {confirm: 'Are you sure?'},
            class: 'btn btn-danger'
        %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/scenes/_guidebook_scene_photos.html.erb
<div class="row">
  <% @photos.each do |photo| %>
    <div class="col-lg-4 col-md-6 mb-4 photo-container">
      <div class="card photo-card h-100">
        <%= render(ViewpointComponent, viewpoint: photo.favoritable_score.present? ? photo.favoritable_score[:favorite] : 0, photo_id: photo.id) %>
        <a class="photo-card-link" href="<%= user_guidebook_scene_photo_path(@user, @guidebook, @scene, id: @photo.id) %>">
          <img class="card-img-top" src="<%= photo_thumb_url(photo) %>" alt="" />
          <div class="card-body">
            <p class="card-text">Latitude: <%= photo.latitude %></p>
            <p class="card-text">Longitude: <%= photo.longitude %></p>
            <p class="card-text">Photo elevation: <%= photo.elevation_meters %>m</p>
            <p class="card-text">Capture time: <%= photo.taken_at.to_formatted_s(:db) %></p>
          </div>
        </a>
      </div>
    </div>
  <% end %>
</div>

app/views/scenes/_guidebook_scenes.html.erb
<h1>Scenes#guidebook_scenes</h1>
<p>Find me in app/views/scenes/guidebook_scenes.html.erb</p>

app/views/scenes/_scene.html.erb
<div id="scene-<%= scene.id %>" class="col-xl-4 col-lg-4 col-md-6 mb-4 scene-item">
  <div class="card photo-card h-100">
    <% if @user.present? && @guidebook.present? && policy(@guidebook).remove_photo? %>
      <%= link_to user_guidebook_scene_remove_photo_path(@user, @guidebook, scene, photo_id: scene.photo.id),
            class: 'close delete_from_book',
            title: 'delete photo from guidebook',
            data: {confirm: 'Are you sure?'},
            method: :delete,
            remote: true do
      %>
          <span aria-hidden="false" class="delete">&times;</span>
      <% end %>
    <% end %>
    <div class="card-body">
      <% if @user.present? %>
        <%= link_to edit_user_guidebook_scene_path(@user, @guidebook, scene) do %>
          <%= fa_icon('cog', class: 'scene-edit float-right') %>
        <% end %>
      <% end %>

      <h4 class="card-text">
        <%= scene.title %>
      </h4>

      <p class="card-text">
        Description: <%= truncate(scene.description, length: 120, separator: ' ') %>
      </p>
      
      <p class="card-text">Position: <%= scene.position %></p>
      <p class="card-text">Tags: 
        <% if scene.tags.size > 0 %>
          <% scene.tags.each_with_index do |tag, i| %>
            <% color = [:info, :danger, :warning, :success][i % 4] %>
            <div class="tag-container tag-badge-<%=color%>">
              <div class="tag-text">
                <%= tag.name %> 
              </div>
            </div>
          <% end %>
        <% else %>
          <small class="nothing-text">nothing</small>
        <% end %>
      </p>
    </div>

    <%= render partial: 'photos/photo',
        locals: {
          photo: scene.photo,
          photo_link: @user.present? ? 
            user_guidebook_scene_photo_path(@user,  @guidebook, scene, id: scene.photo.id) :
            photo_path(scene.photo)
        }
    %>

    <div class="card-footer">
      <small class="text-muted">
        uploaded by: <%= @guidebook.user.name %>
      </small>
    </div>
  </div>

</div>

app/views/scenes/_scenes.html.erb
<% if @user.present? %>
  <div class="float-right">
    <%= link_to 'Add scene', new_user_guidebook_scene_path(user_id: @user.id, guidebook_id: @guidebook.id), class: 'btn btn-primary' %>
  </div>
<% end %>

<h4>Added Scenes</h4>
<div class="h-divider"></div>

<% if @scenes.any? %>
  <div class="sort-wrapper">
    <%= render(
          SortComponent, collection_name: :scenes,
          value: @sort.try(:[], :scenes)
        )
    %>
  </div>
  <div class="row">
    <%= render partial: 'scenes/scene', collection: @scenes %>
  </div>
<% else %>
  <p class="card-text">Nothing</p>
<% end %> 

app/views/scenes/_user_scenes.html.erb
<div class="float-right">
  <%= link_to 'Add scene', new_user_guidebook_scene_path(user_id: @user.id, guidebook_id: @guidebook.id), class: 'btn btn-primary' %>
</div>

<h4>Added Scenes</h4>
<div class="h-divider"></div>

<% if @scenes.any? %>
  <div class="sort-wrapper">
    <%= render(
          SortComponent, collection_name: :scenes,
          value: @sort.try(:[], :scenes)
        )
    %>
  </div>
  <div class="row">
    <%= render partial: 'scenes/user_scene', collection: @scenes %>
  </div>
<% else %>
  <p class="card-text">Nothing</p>
<% end %> 

app/views/scenes/create.html.erb
<h1>Scenes#create</h1>
<p>Find me in app/views/scenes/create.html.erb</p>

app/views/scenes/create.js.erb
<% if @scene.errors.any? %>
  var container = $('#createSceneModal .form-errors');
  container.html('<%= j form_errors_for @scene %>');
<% else %>
  $('#createSceneModal').modal('hide');
  var messages = $('.flash-messages');
  messages.html('<%= j render partial: "shared/flash_messages" %>');
  //add link to scenes list
  var scenesList = $('#scenesList');
  var link = '<%=  link_to @scene.name,
                          add_item_user_scene_path(@scene.user, @scene, item_id: @photo.id),
                          class: 'dropdown-item',
                          remote: true,
                          method: :post %>'
  scenesList.append(link);
<% end %>scenesList

app/views/scenes/destroy.html.erb
<h1>Scenes#destroy</h1>
<p>Find me in app/views/scenes/destroy.html.erb</p>

app/views/scenes/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="my-4"><%= title 'New Scene' %></h1>
    <% description app_description %>
  </div>

  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/scenes/select_scene_photo.js.erb
$("#guidebook-scene-photo").html("<%= escape_javascript(render partial: 'photos/photo', locals: {photo: @photo}) %>");

app/views/scenes/update.html.erb
<h1>Scenes#update</h1>
<p>Find me in app/views/scenes/update.html.erb</p>

app/views/scenes/user.show.html.erb
<% content_for :meta_title do %>
  <% @scene.position %>
<% end %>

<% content_for :meta_description do %>
  <% @scene.description %>
<% end %>

<div class="row">
  <div class="py-5 col-lg-12">
    <div class="card">

      <div class="card-header">
        <div class="row">

          <h1 class="col-lg-10 col-sm-12">
            <%= title "#{@scene.position}th scenen" %>
          </h1>
          <% description @scene.description %>

          <% if policy(@scene).update? %>
            <div class="col-lg-1 col-sm-6">
              <div class="float-right">
                <%= link_to 'Edit',
                      edit_user_guidebook_scene_path(
                          @user, @guidebook, @scene
                      ),
                      class: 'btn btn-warning mt-2'
                %>
              </div>
            </div>
          <% end %>

          <% if policy(@scene).destroy? %>
            <div class="col-lg-1 col-sm-6">
              <div class="float-right">
                <%= link_to 'Delete',
                      url_for(action: :destroy, id: @scene.id),
                      method: :delete,
                      data: {confirm: 'Are you sure?'},
                      class: 'btn btn-danger mt-2'
                %>
              </div>
            </div>
          <% end %>

        </div>
      </div>

      <div class="card-body">
        <h3 class="card-title"><%= @scene.position %></h3>
        <%= render partial: 'scenes/user_scene', locals: { scene: @scene } %>
      </div>
    </div>
  </div>
</div>

<div class="form-group">
  <%= link_to 'Back', :back, class: 'btn btn-success' %>
</div>

app/views/scenes/user_index.html.erb
<%= render 'user_scenes' %>